import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

const gumletLoader = ({ src, width, quality }) => {
  return `https://webfolderanu.gumlet.io/${src}?w=${width}&q=${quality || 75}`
}


const MyImage = (props) => {
  return (
    <Image
      loader={gumletLoader}
      src="spiritual.jpg"
      alt="Picture of the author"
      width={500}
      height={500}
    />
  )
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Gumlet Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Gumlet NextJS</h1>
      <MyImage/>

      

    </div>
  )
}
